### ISSUE TITLE
After clicking 2 times on a field, it becomes white

### ISSUE THREAD

**Issue by marcb4** [marcb4/nerdquiztafel#1]
After I click 2 times on a field it becomes white and doesn't stay the color it was before first clicking

![image](https://user-images.githubusercontent.com/48357999/92497979-55185f00-f1fa-11ea-9d0d-be13129eb2da.png)

**Comment by svolume** [comment]
it seems to be intentional, see below 
https://github.com/marcb4/nerdquiztafel/blob/f42efa1cd25379073ed2dc4308616af7c1524e11/src/js/index.js#L4-L13
when you only use the else part, it works as expected.

**Comment by marcb4** [comment]
fixed by adding a variable to store current color
